/**
 * 话题专属语块池 Part 4：收尾覆盖（pools-v4）。
 */
import type { PoolChunk } from "./topic_pools";

export const TOPIC_POOLS_4: Record<string, PoolChunk[]> = {
  收尾: [
    { display: "shop for shoes online", meaningZh: "网购鞋子", unitType: "collocation", difficulty: "intermediate", exampleEn: "I shop for shoes online when they're on sale.", dims: ["buying", "cons"] },
    { display: "a strict no-phones policy", meaningZh: "严格的禁手机规定", unitType: "collocation", difficulty: "advanced", exampleEn: "Our family has a strict no-phones policy at dinner.", dims: ["phone-ban", "rule"] },
    { display: "be all smiles", meaningZh: "满脸笑容", unitType: "idiom", difficulty: "advanced", exampleEn: "Everyone was all smiles at the party.", dims: ["smiling", "why-smiling"] },
    { display: "the latest gadgets", meaningZh: "最新款的电子产品", unitType: "collocation", difficulty: "intermediate", exampleEn: "He always owns the latest gadgets.", dims: ["gadgets", "what-device"] },
    { display: "a bike ride around the lake", meaningZh: "环湖骑行", unitType: "collocation", difficulty: "intermediate", exampleEn: "We went for a bike ride around the lake.", dims: ["bike-trips", "trip"] },
    { display: "make a tough decision", meaningZh: "做艰难的决定", unitType: "collocation", difficulty: "intermediate", exampleEn: "I had to make a tough decision last year.", dims: ["decisions", "what-decision"] },
    { display: "a blockbuster movie", meaningZh: "大片", unitType: "collocation", difficulty: "intermediate", exampleEn: "We watched a blockbuster movie last night.", dims: ["movies", "movie"] },
    { display: "doodle in the margins", meaningZh: "在页边涂鸦", unitType: "collocation", difficulty: "advanced", exampleEn: "As a kid, I doodled in the margins of my books.", dims: ["drawing", "childhood"] },
    { display: "a small vegetable patch", meaningZh: "小菜园", unitType: "collocation", difficulty: "intermediate", exampleEn: "Grandpa keeps a small vegetable patch.", dims: ["home-garden", "growing"] },
    { display: "mind your manners in public", meaningZh: "在公共场合注意举止", unitType: "collocation", difficulty: "intermediate", exampleEn: "Mind your manners in public places.", dims: ["behaviors", "etiquette"] },
    { display: "a family outing", meaningZh: "家庭出游", unitType: "collocation", difficulty: "basic", exampleEn: "We have a family outing every month.", dims: ["outing", "activities"] },
    { display: "follow the school rules", meaningZh: "遵守校规", unitType: "collocation", difficulty: "basic", exampleEn: "Students follow the school rules.", dims: ["obeying", "rules"] },
    { display: "live sports events", meaningZh: "现场体育赛事", unitType: "collocation", difficulty: "intermediate", exampleEn: "Live sports events are so exciting.", dims: ["events", "event"] },
    { display: " glued to my phone", meaningZh: "手机不离手", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "I'm often glued to my phone on the metro.", dims: ["phone", "dependency"] },
    { display: "pay in cash", meaningZh: "用现金支付", unitType: "collocation", difficulty: "basic", exampleEn: "Some stalls only take cash.", dims: ["cash", "payment"] },
    { display: "sort out an argument", meaningZh: "化解争吵", unitType: "collocation", difficulty: "advanced", exampleEn: "A quick apology sorts out most arguments.", dims: ["arguments", "resolution"] },
    { display: "an ad that stuck in my mind", meaningZh: "印象深刻的广告", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "There's an ad that stuck in my mind since childhood.", dims: ["impression", "memorable-ad"] },
    { display: "take short breaks", meaningZh: "短暂休息", unitType: "collocation", difficulty: "basic", exampleEn: "I take short breaks every hour.", dims: ["breaks", "occasions"] },
    { display: "stay abroad for a few months", meaningZh: "在国外待几个月", unitType: "collocation", difficulty: "intermediate", exampleEn: "I stayed abroad for a few months last year.", dims: ["foreign-stay", "duration"] },
    { display: "let your creativity flow", meaningZh: "释放创造力", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Drawing lets your creativity flow.", dims: ["imagination", "creativity"] },
    { display: "the main character", meaningZh: "主角", unitType: "collocation", difficulty: "basic", exampleEn: "The main character is a young detective.", dims: ["person", "plot"] },
    { display: "daily duties", meaningZh: "日常工作", unitType: "collocation", difficulty: "intermediate", exampleEn: "My daily duties include stocktaking.", dims: ["duties", "day-to-day"] },
    { display: "how we were raised", meaningZh: "我们的成长方式", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "How we were raised shapes our habits.", dims: ["upbringing", "reasons"] },
    { display: "hit the shops", meaningZh: "去逛街购物", unitType: "idiom", difficulty: "intermediate", exampleEn: "We hit the shops on the weekend.", dims: ["shopping", "activities"] },
    { display: "shoot to fame", meaningZh: "一举成名", unitType: "collocation", difficulty: "advanced", exampleEn: "She shot to fame after that show.", dims: ["fame", "viral"] },
    { display: "a mix of talent and luck", meaningZh: "天赋与运气并存", unitType: "collocation", difficulty: "intermediate", exampleEn: "Success is a mix of talent and luck.", dims: ["talent-luck", "reasons"] },
    { display: "the media spotlight", meaningZh: "媒体聚光灯", unitType: "collocation", difficulty: "advanced", exampleEn: "The media spotlight never fades for stars.", dims: ["media", "pressure"] },
    { display: "smartphones changed everything", meaningZh: "智能手机改变了一切", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Smartphones changed everything about how we talk.", dims: ["phones", "changes"] },
    { display: "regulate screen time for kids", meaningZh: "监管儿童屏幕时间", unitType: "collocation", difficulty: "advanced", exampleEn: "Parents regulate screen time for kids.", dims: ["regulation", "guidance"] },
    { display: "avoid the crowds", meaningZh: "避开人流", unitType: "collocation", difficulty: "intermediate", exampleEn: "I go early to avoid the crowds.", dims: ["crowds", "coping"] },
    { display: "sneaker collection", meaningZh: "球鞋收藏", unitType: "collocation", difficulty: "intermediate", exampleEn: "My cousin owns a huge sneaker collection.", dims: ["shoes", "collection"] },
    { display: "drive on the highway", meaningZh: "在高速上开车", unitType: "collocation", difficulty: "basic", exampleEn: "I love driving on the highway at night.", dims: ["driving", "experiences"] },
    { display: "rush-hour traffic", meaningZh: "高峰期交通", unitType: "collocation", difficulty: "intermediate", exampleEn: "Rush-hour traffic drives me crazy.", dims: ["traffic", "activities"] },
    { display: "pastel shades", meaningZh: "柔和色调", unitType: "collocation", difficulty: "advanced", exampleEn: "I prefer pastel shades in summer.", dims: ["colors", "preferences"] },
    { display: "a scenic coastal drive", meaningZh: "沿海风景自驾", unitType: "collocation", difficulty: "advanced", exampleEn: "We took a scenic coastal drive last summer.", dims: ["road-trips", "scenery"] },
    { display: "an evening stroll", meaningZh: "傍晚散步", unitType: "collocation", difficulty: "intermediate", exampleEn: "An evening stroll helps me sleep.", dims: ["walks", "benefits"] },
    { display: "use headphones on the bus", meaningZh: "在公交上戴耳机", unitType: "collocation", difficulty: "basic", exampleEn: "I use headphones on the bus to relax.", dims: ["using", "occasions"] },
    { display: "carry earbuds everywhere", meaningZh: "耳机不离身", unitType: "collocation", difficulty: "intermediate", exampleEn: "I carry earbuds everywhere I go.", dims: ["carrying", "habits"] },
    { display: "minimalist decor", meaningZh: "极简布置", unitType: "collocation", difficulty: "advanced", exampleEn: "I prefer minimalist decor at home.", dims: ["decor", "styles"] },
    { display: "gaze at the stars", meaningZh: "仰望星空", unitType: "collocation", difficulty: "intermediate", exampleEn: "We gazed at the stars from the cabin porch.", dims: ["stargazing", "experiences"] },
    { display: "a sci-fi nerd", meaningZh: "科幻迷", unitType: "collocation", difficulty: "advanced", exampleEn: "My brother is a total sci-fi nerd.", dims: ["sci-fi", "types"] },
    { display: "graphic T-shirts", meaningZh: "带图案的T恤", unitType: "collocation", difficulty: "intermediate", exampleEn: "I live in graphic T-shirts.", dims: ["t-shirts", "kinds"] },
    { display: "compare prices before buying", meaningZh: "买前比价", unitType: "collocation", difficulty: "intermediate", exampleEn: "I compare prices before buying anything big.", dims: ["choosing", "considerations"] },
    { display: "crack a joke to break the ice", meaningZh: "讲笑话活跃气氛", unitType: "collocation", difficulty: "advanced", exampleEn: "He cracked a joke to break the ice.", dims: ["jokes", "atmosphere"] },
    { display: "a comedy fan", meaningZh: "喜剧迷", unitType: "collocation", difficulty: "basic", exampleEn: "I'm a big comedy fan.", dims: ["comedies", "favorites"] },
    { display: "a great sense of humor", meaningZh: "很好的幽默感", unitType: "collocation", difficulty: "intermediate", exampleEn: "A great sense of humor makes people likable.", dims: ["humor", "qualities"] },
    { display: "play a musical instrument", meaningZh: "演奏乐器", unitType: "collocation", difficulty: "basic", exampleEn: "I play two musical instruments.", dims: ["instruments", "talent"] },
    { display: "cheer someone on", meaningZh: "为某人打气", unitType: "phrasal_verb", difficulty: "intermediate", exampleEn: "I cheered him on during the marathon.", dims: ["encouraging", "support"] },
    { display: "visit nearby cities", meaningZh: "游览周边城市", unitType: "collocation", difficulty: "basic", exampleEn: "We visit nearby cities on long weekends.", dims: ["cities", "plans"] },
    { display: "homes with character", meaningZh: "有个性的房子", unitType: "collocation", difficulty: "advanced", exampleEn: "I love homes with character.", dims: ["homes", "why-like"] },
    { display: "propose a new law", meaningZh: "提出新法律", unitType: "collocation", difficulty: "intermediate", exampleEn: "I would propose a new law on recycling.", dims: ["new-laws", "what-law"] },
    { display: "law enforcement", meaningZh: "执法", unitType: "collocation", difficulty: "advanced", exampleEn: "Law enforcement needs funding too.", dims: ["enforcement", "challenges"] },
    { display: "an early-morning routine", meaningZh: "晨间例行安排", unitType: "collocation", difficulty: "intermediate", exampleEn: "An early-morning routine keeps me organized.", dims: ["early-rising", "routines"] },
    { display: "no reply for days", meaningZh: "好几天没有回复", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "There was no reply for days.", dims: ["no-reply", "feelings"] },
    { display: "two-way communication", meaningZh: "双向沟通", unitType: "collocation", difficulty: "advanced", exampleEn: "Good parenting needs two-way communication.", dims: ["communication", "ways"] },
    { display: "school subjects", meaningZh: "学校科目", unitType: "collocation", difficulty: "basic", exampleEn: "School subjects teach different ways of thinking.", dims: ["schools", "subjects"] },
    { display: "a huge success", meaningZh: "巨大的成功", unitType: "collocation", difficulty: "basic", exampleEn: "The event was a huge success.", dims: ["success", "result"] },
    { display: "lifelong learning", meaningZh: "终身学习", unitType: "collocation", difficulty: "advanced", exampleEn: "Lifelong learning keeps your mind sharp.", dims: ["education", "importance"] },
    { display: "a live concert", meaningZh: "现场演唱会", unitType: "collocation", difficulty: "basic", exampleEn: "A live concert hits different.", dims: ["concert", "experience"] },
    { display: "cut down on single-use plastic", meaningZh: "减少一次性塑料", unitType: "collocation", difficulty: "advanced", exampleEn: "We cut down on single-use plastic last year.", dims: ["env-actions", "individual"] },
    { display: "a complete change of heart", meaningZh: "彻底改变想法", unitType: "idiom", difficulty: "advanced", exampleEn: "I had a complete change of heart about city life.", dims: ["turning-point", "trigger"] },
    { display: "make a shopping list", meaningZh: "列购物清单", unitType: "collocation", difficulty: "basic", exampleEn: "Make a shopping list before you go.", dims: ["shopping-list", "habits"] },
    { display: "science in everyday life", meaningZh: "日常生活中的科学", unitType: "collocation", difficulty: "intermediate", exampleEn: "Science in everyday life is everywhere — even cooking.", dims: ["real-life", "application"] },
    { display: "sing karaoke with friends", meaningZh: "和朋友唱K", unitType: "collocation", difficulty: "intermediate", exampleEn: "We sing karaoke with friends after exams.", dims: ["audience", "occasions"] },
    { display: "wireless vs wired", meaningZh: "无线与有线", unitType: "collocation", difficulty: "intermediate", exampleEn: "Wireless vs wired — I choose wireless for freedom.", dims: ["wired-wireless", "preference"] },
    { display: "share the harvest with neighbors", meaningZh: "与邻居分享收成", unitType: "collocation", difficulty: "advanced", exampleEn: "We share the harvest with neighbors every autumn.", dims: ["harvest", "sharing"] },
    { display: "a no-phone dinner", meaningZh: "无手机晚餐", unitType: "collocation", difficulty: "intermediate", exampleEn: "We have a no-phone dinner every Friday.", dims: ["rule", "phone-ban"] },
    { display: "a blockbuster hit", meaningZh: "票房爆款", unitType: "collocation", difficulty: "intermediate", exampleEn: "The movie became a blockbuster hit.", dims: ["plot", "success"] },
    { display: "a gifted child painter", meaningZh: "有天赋的小画家", unitType: "collocation", difficulty: "advanced", exampleEn: "She's a gifted child painter.", dims: ["talent", "works"] },
    { display: "get easier with practice", meaningZh: "越练越容易", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Growing vegetables gets easier with practice.", dims: ["easy-or-not", "difficulty"] },
    { display: "grow herbs on the balcony", meaningZh: "在阳台种香草", unitType: "collocation", difficulty: "intermediate", exampleEn: "I grow herbs on the balcony.", dims: ["interest", "keeping"] },
    { display: "know the basics of gardening", meaningZh: "懂园艺基础", unitType: "collocation", difficulty: "intermediate", exampleEn: "I know the basics of gardening from my grandma.", dims: ["knowledge", "learning"] },
    { display: "work a short stint abroad", meaningZh: "短期海外工作", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "I worked a short stint abroad last year.", dims: ["country", "foreign-stay"] },
    { display: "settle down abroad", meaningZh: "定居国外", unitType: "collocation", difficulty: "advanced", exampleEn: "Some friends settled down abroad.", dims: ["permanent", "plans"] },
    { display: "car colours matter more than you think", meaningZh: "车颜色比你想的重要", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Car colours matter more than you think.", dims: ["colors", "importance"] },
    { display: "smart devices everywhere", meaningZh: "到处都是智能设备", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Smart devices are everywhere now.", dims: ["devices", "technology"] },
    { display: "crowded tourist spots", meaningZh: "拥挤的景点", unitType: "collocation", difficulty: "intermediate", exampleEn: "Avoid crowded tourist spots on holidays.", dims: ["crowded-places", "places"] },
    { display: "cash is still king in some places", meaningZh: "有些地方现金仍是王道", unitType: "sentence_frame", difficulty: "advanced", exampleEn: "Cash is still king in small towns.", dims: ["payment", "cash"] },
    { display: "grew up together", meaningZh: "一起长大", unitType: "collocation", difficulty: "basic", exampleEn: "We grew up together in the same alley.", dims: ["how-met", "childhood-friends"] },
    { display: "science fairs", meaningZh: "科学展", unitType: "collocation", difficulty: "intermediate", exampleEn: "Science fairs made school fun.", dims: ["exhibits", "memories"] },
    { display: "watch live streams", meaningZh: "看直播", unitType: "collocation", difficulty: "intermediate", exampleEn: "I watch live streams instead of TV.", dims: ["programs", "entertainment"] },
    { display: "new housing developments", meaningZh: "新住宅开发", unitType: "collocation", difficulty: "advanced", exampleEn: "New housing developments changed the skyline.", dims: ["construction", "areas"] },
  ],
};
