/**
 * 话题专属语块池 Part 2：覆盖剩余 blueprint 维度（pools-v2）。
 */
import type { PoolChunk } from "./topic_pools";

export const TOPIC_POOLS_2: Record<string, PoolChunk[]> = {
  广告与媒体: [
    { display: "be aimed at children", meaningZh: "针对儿童", unitType: "collocation", difficulty: "intermediate", exampleEn: "Some ads are clearly aimed at children.", dims: ["children"] },
    { display: "support the local economy", meaningZh: "支持本地经济", unitType: "collocation", difficulty: "intermediate", exampleEn: "Advertising supports the local economy.", dims: ["economy", "economy-role"] },
    { display: "it interrupts your conversation", meaningZh: "打断你聊天", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "Pop-ups interrupt your conversation online.", dims: ["conversation", "annoyance"] },
    { display: "a flexible schedule", meaningZh: "灵活的时间安排", unitType: "collocation", difficulty: "intermediate", exampleEn: "A flexible schedule matters to me.", dims: ["flexibility", "flexible"] },
    { display: "health benefits", meaningZh: "健康益处", unitType: "collocation", difficulty: "basic", exampleEn: "It has real health benefits.", dims: ["health", "health-benefits"] },
    { display: "teach kids empathy", meaningZh: "培养同理心", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Animal stories teach kids empathy.", dims: ["empathy", "lessons"] },
    { display: "decorate the room", meaningZh: "布置房间", unitType: "collocation", difficulty: "basic", exampleEn: "Mirrors can decorate the room nicely.", dims: ["decor", "decoration", "decoration-idea"] },
    { display: "book flights in advance", meaningZh: "提前订机票", unitType: "collocation", difficulty: "intermediate", exampleEn: "I book flights in advance to save money.", dims: ["bookings", "planning-ways"] },
    { display: "a booming industry", meaningZh: "蓬勃发展的行业", unitType: "collocation", difficulty: "advanced", exampleEn: "Pet care is a booming industry.", dims: ["industry", "economy", "jobs"] },
    { display: "the ideal length", meaningZh: "理想时长", unitType: "collocation", difficulty: "intermediate", exampleEn: "The ideal length of a holiday varies.", dims: ["ideal-length"] },
    { display: "repetitive ads", meaningZh: "重复的广告", unitType: "collocation", difficulty: "intermediate", exampleEn: "Repetitive ads just annoy people.", dims: ["repetition", "annoyance"] },
    { display: "tell a good story", meaningZh: "讲个好故事", unitType: "collocation", difficulty: "intermediate", exampleEn: "Good ads tell a good story.", dims: ["storytelling", "success", "factors"] },
    { display: "do your research", meaningZh: "做足功课", unitType: "collocation", difficulty: "intermediate", exampleEn: "I do my research before a trip.", dims: ["research", "planning-ways"] },
  ],
  规则与社会: [
    { display: "clean energy", meaningZh: "清洁能源", unitType: "collocation", difficulty: "intermediate", exampleEn: "Clean energy is the future.", dims: ["energy", "tech-ways"] },
    { display: "close the gaps", meaningZh: "弥补不足", unitType: "collocation", difficulty: "advanced", exampleEn: "New laws aim to close the gaps.", dims: ["gaps", "improvements"] },
    { display: "the older generation", meaningZh: "老一辈人", unitType: "collocation", difficulty: "basic", exampleEn: "The older generation has different manners.", dims: ["generations", "generational-diff"] },
    { display: "basic infrastructure", meaningZh: "基础设施", unitType: "collocation", difficulty: "advanced", exampleEn: "Basic infrastructure makes cycling safer.", dims: ["infrastructure", "facilities"] },
    { display: "monitor air quality", meaningZh: "监测空气质量", unitType: "collocation", difficulty: "advanced", exampleEn: "Cities monitor air quality daily.", dims: ["monitoring", "tech-ways"] },
    { display: "tighten regulations", meaningZh: "收紧监管", unitType: "collocation", difficulty: "advanced", exampleEn: "The government tightened regulations on ads.", dims: ["policies", "regulate", "regulations"] },
    { display: "a matter of time", meaningZh: "只是时间问题", unitType: "collocation", difficulty: "intermediate", exampleEn: "Global agreement is a matter of time.", dims: ["possibility", "future"] },
    { display: "a real eye-opener", meaningZh: "大开眼界的事", unitType: "collocation", difficulty: "advanced", exampleEn: "The documentary was a real eye-opener.", dims: ["severity", "awareness"] },
    { display: "total chaos", meaningZh: "一片混乱", unitType: "collocation", difficulty: "intermediate", exampleEn: "Without laws, there would be total chaos.", dims: ["without-laws", "order", "problems"] },
    { display: "affect children's behavior", meaningZh: "影响儿童行为", unitType: "collocation", difficulty: "intermediate", exampleEn: "Violent games affect children's behavior.", dims: ["children", "negative-effects"] },
    { display: "psychological pressure", meaningZh: "心理压力", unitType: "collocation", difficulty: "advanced", exampleEn: "Deadlines create psychological pressure.", dims: ["psychology", "pressure"] },
  ],
  工作或学习: [
    { display: "balance work and study", meaningZh: "平衡工作与学习", unitType: "collocation", difficulty: "intermediate", exampleEn: "It's hard to balance work and study.", dims: ["distribution", "balance"] },
    { display: "full of energy", meaningZh: "精力充沛", unitType: "collocation", difficulty: "basic", exampleEn: "Mornings leave me full of energy.", dims: ["energy", "mood"] },
    { display: "exam season", meaningZh: "考试季", unitType: "collocation", difficulty: "intermediate", exampleEn: "Exam season is coming soon.", dims: ["exams", "time"] },
    { display: "miss being a student", meaningZh: "想念学生时代", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "I really miss being a student.", dims: ["miss-or-not", "aspects"] },
    { display: "get your priorities straight", meaningZh: "理清优先级", unitType: "idiom", difficulty: "advanced", exampleEn: "Get your priorities straight first.", dims: ["priorities", "most-important"] },
    { display: "be realistic about", meaningZh: "对…现实一点", unitType: "collocation", difficulty: "advanced", exampleEn: "Be realistic about your budget.", dims: ["realism", "conditions"] },
    { display: "return the favor", meaningZh: "回报对方", unitType: "collocation", difficulty: "advanced", exampleEn: "I helped him to return the favor.", dims: ["reciprocation", "help"] },
    { display: "be satisfied with", meaningZh: "对…满意", unitType: "collocation", difficulty: "intermediate", exampleEn: "I'm satisfied with my progress.", dims: ["satisfaction", "like-dislike"] },
    { display: "switch to another job", meaningZh: "换一份工作", unitType: "collocation", difficulty: "intermediate", exampleEn: "I'm planning to switch to another job.", dims: ["target", "wish", "plans"] },
    { display: "work freelance", meaningZh: "做自由职业", unitType: "collocation", difficulty: "advanced", exampleEn: "I work freelance as a designer.", dims: ["freedom", "alternative"] },
  ],
  名气媒体: [
    { display: "gain a huge following", meaningZh: "收获大批粉丝", unitType: "collocation", difficulty: "advanced", exampleEn: "Influencers gain a huge following overnight.", dims: ["accessibility", "viral", "viral-fame"] },
    { display: "stay down to earth", meaningZh: "保持接地气", unitType: "collocation", difficulty: "advanced", exampleEn: "Famous people should stay down to earth.", dims: ["behavior", "essence", "now-view"] },
    { display: "keep pushing forward", meaningZh: "坚持向前", unitType: "collocation", difficulty: "intermediate", exampleEn: "Keep pushing forward despite setbacks.", dims: ["persistence", "efforts"] },
    { display: "thrive under pressure", meaningZh: "在压力下表现出色", unitType: "collocation", difficulty: "advanced", exampleEn: "Some people thrive under pressure.", dims: ["pressure", "happiness", "tradeoffs"] },
    { display: "fame comes and goes", meaningZh: "名气来来去去", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Fame comes and goes quickly these days.", dims: ["type", "viral-fame", "essence"] },
  ],
  家庭与教育: [
    { display: "help with homework", meaningZh: "辅导作业", unitType: "collocation", difficulty: "basic", exampleEn: "Parents help with homework after dinner.", dims: ["academic", "parental-role", "school-coop"] },
    { display: "keep the lines of communication open", meaningZh: "保持沟通畅通", unitType: "idiom", difficulty: "advanced", exampleEn: "Keep the lines of communication open with your kids.", dims: ["communication", "boundaries"] },
    { display: "go too far", meaningZh: "做得过火", unitType: "collocation", difficulty: "intermediate", exampleEn: "Some parents go too far with rules.", dims: ["degree", "strict-or-not", "drawbacks"] },
    { display: "in the long run", meaningZh: "长远来看", unitType: "functional_expression", difficulty: "intermediate", exampleEn: "In the long run, kindness pays off.", dims: ["long-term", "future"] },
    { display: "learn from mistakes", meaningZh: "从错误中学习", unitType: "collocation", difficulty: "intermediate", exampleEn: "Children learn from mistakes.", dims: ["mistakes", "lesson"] },
    { display: "a small reward", meaningZh: "小奖励", unitType: "collocation", difficulty: "basic", exampleEn: "A small reward works wonders.", dims: ["reward-or-not", "rewards"] },
    { display: "express themselves", meaningZh: "表达自己", unitType: "collocation", difficulty: "intermediate", exampleEn: "Art helps kids express themselves.", dims: ["expression", "creativity"] },
    { display: "a proud moment", meaningZh: "骄傲的时刻", unitType: "collocation", difficulty: "intermediate", exampleEn: "Graduation was a proud moment for my parents.", dims: ["achievements", "occasions"] },
  ],
  老师与校园: [
    { display: "consider teaching as a career", meaningZh: "考虑以教书为职业", unitType: "collocation", difficulty: "intermediate", exampleEn: "I've considered teaching as a career.", dims: ["intent", "career-view", "future-plan"] },
    { display: "patience and passion", meaningZh: "耐心与热情", unitType: "collocation", difficulty: "intermediate", exampleEn: "Teaching takes patience and passion.", dims: ["required-qualities", "teacher-qualities", "challenges"] },
    { display: "lose track of someone", meaningZh: "和某人失去联系", unitType: "collocation", difficulty: "advanced", exampleEn: "I lost track of my primary school teacher.", dims: ["still-in-touch", "reunion", "reasons-loss"] },
    { display: "a teaching style that suits me", meaningZh: "适合我的教学风格", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "She had a teaching style that suited me.", dims: ["teaching-style", "likes-reasons"] },
    { display: "his words stuck with me", meaningZh: "他的话我一直记得", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "His words stuck with me for years.", dims: ["words-deeds", "memories", "influence"] },
    { display: "still remember someone vividly", meaningZh: "依然清晰记得某人", unitType: "collocation", difficulty: "intermediate", exampleEn: "I still remember my first teacher vividly.", dims: ["still-remember", "memories"] },
  ],
  工作与成功: [
    { display: "a growing industry", meaningZh: "成长的行业", unitType: "collocation", difficulty: "intermediate", exampleEn: "AI is a growing industry.", dims: ["industries", "trends"] },
    { display: "stay motivated", meaningZh: "保持动力", unitType: "collocation", difficulty: "intermediate", exampleEn: "Small wins keep me motivated.", dims: ["motivation", "drive"] },
    { display: "a healthy sense of ambition", meaningZh: "健康的进取心", unitType: "collocation", difficulty: "advanced", exampleEn: "A healthy sense of ambition pushes you forward.", dims: ["healthy-ambition", "balance"] },
    { display: "grow both personally and professionally", meaningZh: "个人与职业双成长", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "The job helped me grow both personally and professionally.", dims: ["growth", "influence"] },
    { display: "see both sides", meaningZh: "看到两面", unitType: "collocation", difficulty: "intermediate", exampleEn: "I try to see both sides of promotion.", dims: ["perspective", "comparison"] },
    { display: "under constant pressure", meaningZh: "承受持续压力", unitType: "collocation", difficulty: "intermediate", exampleEn: "Managers are under constant pressure.", dims: ["pressure", "tradeoffs"] },
    { display: "follow in someone's footsteps", meaningZh: "走某人的老路、继承", unitType: "idiom", difficulty: "advanced", exampleEn: "He followed in his father's footsteps.", dims: ["business", "identity"] },
  ],
  娱乐电影音乐: [
    { display: "carry the whole film", meaningZh: "撑起整部电影", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "One great actor can carry the whole film.", dims: ["actors", "guarantee", "factors"] },
    { display: "a catchy rhythm", meaningZh: "洗脑的节奏", unitType: "collocation", difficulty: "intermediate", exampleEn: "The song has a catchy rhythm.", dims: ["rhythm", "music"] },
    { display: "subtitles", meaningZh: "字幕", unitType: "collocation", difficulty: "intermediate", exampleEn: "I watch foreign films with subtitles.", dims: ["foreign", "domestic"] },
    { display: "the plot twist", meaningZh: "剧情反转", unitType: "collocation", difficulty: "advanced", exampleEn: "The plot twist surprised everyone.", dims: ["story", "plot"] },
    { display: "music gets me pumped", meaningZh: "音乐让我兴奋", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Upbeat music gets me pumped for workouts.", dims: ["motivation", "effect"] },
  ],
  晨间: [
    { display: "grab a quick breakfast", meaningZh: "匆忙吃个早餐", unitType: "collocation", difficulty: "intermediate", exampleEn: "I grab a quick breakfast before work.", dims: ["breakfast", "routines"] },
    { display: "beat the morning rush", meaningZh: "赶在早高峰前", unitType: "collocation", difficulty: "advanced", exampleEn: "I leave early to beat the morning rush.", dims: ["commute", "weekdays"] },
    { display: "not a morning person", meaningZh: "不是早起型的人", unitType: "idiom", difficulty: "intermediate", exampleEn: "Honestly, I'm not a morning person.", dims: ["early-bird", "feelings", "difficulties"] },
  ],
  借东西: [
    { display: "small amounts of money", meaningZh: "小额的钱", unitType: "collocation", difficulty: "intermediate", exampleEn: "I only borrow small amounts of money.", dims: ["amounts", "money"] },
    { display: "pay it back on time", meaningZh: "按时归还", unitType: "collocation", difficulty: "intermediate", exampleEn: "I always pay it back on time.", dims: ["repayment", "principles"] },
    { display: "hint that you need it back", meaningZh: "委婉暗示要回来", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "I'd hint that I need it back soon.", dims: ["asking-back", "coping"] },
    { display: "trust works both ways", meaningZh: "信任是相互的", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Trust works both ways when lending things.", dims: ["trust", "attitude"] },
  ],
  规则: [
    { display: "rules give structure", meaningZh: "规则带来秩序感", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "Rules give structure to school life.", dims: ["necessary-rules", "purpose"] },
    { display: "too many rules kill creativity", meaningZh: "太多规则扼杀创造力", unitType: "sentence_frame", difficulty: "advanced", exampleEn: "Too many rules kill creativity.", dims: ["more-rules", "freedom"] },
    { display: "self-discipline matters more", meaningZh: "自律更重要", unitType: "sentence_frame", difficulty: "advanced", exampleEn: "In the end, self-discipline matters more.", dims: ["self-discipline", "attitude"] },
    { display: "dedicated and patient", meaningZh: "敬业且有耐心", unitType: "collocation", difficulty: "intermediate", exampleEn: "Our teacher was dedicated and patient.", dims: ["qualities", "dedicated-teacher"] },
  ],
  分享: [
    { display: "share good news with", meaningZh: "与…分享好消息", unitType: "construction", difficulty: "basic", exampleEn: "I share good news with my best friend first.", dims: ["first-person", "recent-share", "news"] },
    { display: "share the excitement", meaningZh: "分享喜悦", unitType: "collocation", difficulty: "intermediate", exampleEn: "Sharing the excitement doubles the joy.", dims: ["reactions", "their-reaction", "feelings"] },
    { display: "personal stuff stays private", meaningZh: "私事不外传", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Personal stuff stays private.", dims: ["unsuitable", "boundaries"] },
    { display: "teach kids to share", meaningZh: "教孩子分享", unitType: "collocation", difficulty: "basic", exampleEn: "My parents taught me to share early.", dims: ["parental-teaching", "upbringing"] },
  ],
  教育: [
    { display: "a mix of theory and practice", meaningZh: "理论与实践结合", unitType: "collocation", difficulty: "advanced", exampleEn: "A mix of theory and practice works best.", dims: ["combination", "balance", "focus"] },
    { display: "hands-on skills", meaningZh: "动手技能", unitType: "collocation", difficulty: "intermediate", exampleEn: "Hands-on skills get you hired.", dims: ["practical", "skills"] },
    { display: "deep-dive into one subject", meaningZh: "深入钻研一个学科", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Specialising lets you deep-dive into one subject.", dims: ["specialise", "breadth-vs-depth"] },
    { display: "academic knowledge", meaningZh: "学术知识", unitType: "collocation", difficulty: "intermediate", exampleEn: "Academic knowledge builds the foundation.", dims: ["academic", "foundation"] },
    { display: "keep yourself disciplined", meaningZh: "保持自律", unitType: "collocation", difficulty: "intermediate", exampleEn: "Online learning requires you to keep yourself disciplined.", dims: ["self-discipline", "caveats"] },
    { display: "an information overload", meaningZh: "信息过载", unitType: "collocation", difficulty: "advanced", exampleEn: "Too many subjects cause an information overload.", dims: ["too-many", "overload"] },
  ],
  家乡: [
    { display: "plenty of job opportunities", meaningZh: "大量工作机会", unitType: "collocation", difficulty: "intermediate", exampleEn: "Big cities offer plenty of job opportunities.", dims: ["career", "opportunities"] },
    { display: "a booming tech scene", meaningZh: "蓬勃的科技圈", unitType: "collocation", difficulty: "advanced", exampleEn: "My hometown has a booming tech scene.", dims: ["interest", "development"] },
    { display: "keep traditions alive", meaningZh: "让传统延续", unitType: "collocation", difficulty: "advanced", exampleEn: "Festivals keep traditions alive.", dims: ["transmission", "culture"] },
    { display: "grow to love it", meaningZh: "慢慢喜欢上", unitType: "collocation", difficulty: "intermediate", exampleEn: "I've grown to love its quirks.", dims: ["tolerance", "like-or-not"] },
  ],
  居住区域: [
    { display: "a well-known figure", meaningZh: "知名人物", unitType: "collocation", difficulty: "intermediate", exampleEn: "There's a well-known figure in our area.", dims: ["achievements", "famous-people", "meetings"] },
    { display: "chat over the fence", meaningZh: "隔着篱笆聊天（邻里闲聊）", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Neighbors chat over the fence here.", dims: ["interactions", "daily-interactions"] },
    { display: "a noisy street", meaningZh: "喧闹的街道", unitType: "collocation", difficulty: "basic", exampleEn: "We live near a noisy street.", dims: ["noisy-quiet", "sources"] },
  ],
  镜子: [
    { display: "carry a compact mirror", meaningZh: "随身带小镜子", unitType: "collocation", difficulty: "intermediate", exampleEn: "My sister carries a compact mirror everywhere.", dims: ["carry-or-not", "situations"] },
    { display: "make a room look bigger", meaningZh: "让房间显大", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "Mirrors make a room look bigger.", dims: ["decoration", "decoration-idea", "spaces"] },
    { display: "match the decor", meaningZh: "搭配装修风格", unitType: "collocation", difficulty: "advanced", exampleEn: "Pick mirrors that match the decor.", dims: ["styles", "other-decorations"] },
  ],
  植物: [
    { display: "water the plants", meaningZh: "浇花", unitType: "collocation", difficulty: "basic", exampleEn: "I water the plants every morning.", dims: ["care", "habits"] },
    { display: "keep them alive", meaningZh: "把它们养活", unitType: "lexical_chunk", difficulty: "basic", exampleEn: "The hard part is keeping them alive.", dims: ["difficulties", "difficulty"] },
    { display: "know a thing or two about", meaningZh: "略知一二", unitType: "idiom", difficulty: "advanced", exampleEn: "I know a thing or two about growing herbs.", dims: ["knowledge", "skills"] },
    { display: "a symbol of good luck", meaningZh: "好运的象征", unitType: "collocation", difficulty: "intermediate", exampleEn: "Lucky bamboo is a symbol of good luck.", dims: ["meanings", "gifting"] },
  ],
  鞋子: [
    { display: "sneakerhead", meaningZh: "球鞋收藏爱好者", unitType: "collocation", difficulty: "advanced", exampleEn: "My brother is a real sneakerhead.", dims: ["collection", "like-or-not"] },
    { display: "buy online without trying them on", meaningZh: "网上买鞋没法试穿", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "Buying online without trying them on is risky.", dims: ["cons", "risks", "pros"] },
    { display: "comfort comes first", meaningZh: "舒适第一", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "For me, comfort comes first.", dims: ["priority", "preference"] },
  ],
  聊天: [
    { display: "have a proper catch-up", meaningZh: "好好聊聊近况", unitType: "collocation", difficulty: "advanced", exampleEn: "We have a proper catch-up every month.", dims: ["deep-talk", "depth"] },
    { display: "get into an argument", meaningZh: "发生争执", unitType: "collocation", difficulty: "intermediate", exampleEn: "We rarely get into an argument.", dims: ["argue-or-not", "topics"] },
    { display: "group chats", meaningZh: "群聊", unitType: "collocation", difficulty: "basic", exampleEn: "Group chats get noisy fast.", dims: ["group-chat", "channels"] },
  ],
  博物馆: [
    { display: "preserve history and culture", meaningZh: "保存历史文化", unitType: "collocation", difficulty: "advanced", exampleEn: "Museums preserve history and culture.", dims: ["functions", "importance"] },
    { display: "special exhibitions", meaningZh: "特展", unitType: "collocation", difficulty: "intermediate", exampleEn: "They host special exhibitions every quarter.", dims: ["visit", "last-visit", "exhibits"] },
    { display: "appeal to all ages", meaningZh: "老少皆宜", unitType: "collocation", difficulty: "advanced", exampleEn: "Good museums appeal to all ages.", dims: ["visitors", "audience"] },
  ],
  艺术: [
    { display: "a risky career path", meaningZh: "有风险的职业道路", unitType: "collocation", difficulty: "advanced", exampleEn: "Being an artist is a risky career path.", dims: ["life", "wish"] },
    { display: "a natural talent for", meaningZh: "在…有天赋", unitType: "collocation", difficulty: "intermediate", exampleEn: "She has a natural talent for painting.", dims: ["talent", "abilities"] },
    { display: "an acquired taste", meaningZh: "需要慢慢欣赏", unitType: "idiom", difficulty: "advanced", exampleEn: "Modern art is an acquired taste.", dims: ["tastes", "understanding"] },
  ],
  艺术创造力: [
    { display: "fear of being judged", meaningZh: "怕被评价", unitType: "collocation", difficulty: "intermediate", exampleEn: "Fear of being judged kills creativity.", dims: ["fear", "reasons"] },
    { display: "keep the creative spark alive", meaningZh: "保持创造力火花", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Hobbies keep the creative spark alive.", dims: ["keep-creative", "staying creative"] },
    { display: "still play a big role", meaningZh: "依然作用巨大", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Museums still play a big role offline.", dims: ["matter-or-not", "unique-value"] },
    { display: "provoke deep thinking", meaningZh: "引发深思", unitType: "collocation", difficulty: "advanced", exampleEn: "Good art provokes deep thinking.", dims: ["thinking", "inspiration"] },
  ],
  社会行为: [
    { display: "bad manners", meaningZh: "不礼貌的行为", unitType: "collocation", difficulty: "intermediate", exampleEn: "Talking loudly on the bus is bad manners.", dims: ["bad-manners", "public-places"] },
    { display: "bridge the generation gap", meaningZh: "弥合代沟", unitType: "collocation", difficulty: "advanced", exampleEn: "Social media bridges the generation gap.", dims: ["generations", "positive-sides"] },
    { display: "benefit society as a whole", meaningZh: "造福整个社会", unitType: "collocation", difficulty: "advanced", exampleEn: "Small acts of kindness benefit society as a whole.", dims: ["society", "impact"] },
  ],
  汽车: [
    { display: "my dream car", meaningZh: "我的梦想之车", unitType: "collocation", difficulty: "basic", exampleEn: "A small electric car is my dream car.", dims: ["dream-car", "types"] },
    { display: "hold its value", meaningZh: "保值", unitType: "collocation", difficulty: "advanced", exampleEn: "Some cars hold their value well.", dims: ["resale", "factors"] },
    { display: "practical for daily commutes", meaningZh: "日常通勤实用", unitType: "collocation", difficulty: "intermediate", exampleEn: "It's practical for daily commutes.", dims: ["practicality", "features"] },
    { display: "these days", meaningZh: "如今", unitType: "functional_expression", difficulty: "basic", exampleEn: "These days I take the metro.", dims: ["now", "changes"] },
  ],
  衣服: [
    { display: "shop for clothes", meaningZh: "买衣服", unitType: "collocation", difficulty: "basic", exampleEn: "I shop for clothes twice a year.", dims: ["buying", "frequency"] },
    { display: "pastel colors", meaningZh: "柔和的浅色", unitType: "collocation", difficulty: "advanced", exampleEn: "I like pastel colors in summer.", dims: ["colors", "styles"] },
    { display: "comfort over style", meaningZh: "舒适优先于款式", unitType: "collocation", difficulty: "intermediate", exampleEn: "I choose comfort over style.", dims: ["comfort", "preference"] },
  ],
  团体运动: [
    { display: "team spirit", meaningZh: "团队精神", unitType: "collocation", difficulty: "intermediate", exampleEn: "Team spirit wins games.", dims: ["cooperation", "takeaways"] },
    { display: "play on a local team", meaningZh: "在本地球队打球", unitType: "collocation", difficulty: "intermediate", exampleEn: "I play on a local basketball team.", dims: ["participation", "role", "team-experience"] },
  ],
  人多的地方: [
    { display: "packed with people", meaningZh: "挤满了人", unitType: "collocation", difficulty: "intermediate", exampleEn: "The mall was packed with people.", dims: ["crowded-or-not", "story"] },
    { display: "most people avoid...", meaningZh: "大多数人会避开…", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Most people avoid rush-hour crowds.", dims: ["majority", "reasons"] },
  ],
  种菜: [
    { display: "grow your own vegetables", meaningZh: "自己种菜", unitType: "collocation", difficulty: "intermediate", exampleEn: "Growing your own vegetables is rewarding.", dims: ["easy-or-not", "interest"] },
    { display: "it takes patience", meaningZh: "需要耐心", unitType: "sentence_frame", difficulty: "basic", exampleEn: "Gardening takes patience.", dims: ["knowledge", "difficulty"] },
  ],
  科技: [
    { display: "steep learning curve", meaningZh: "陡峭的学习曲线", unitType: "collocation", difficulty: "advanced", exampleEn: "Some apps have a steep learning curve.", dims: ["complexity", "reasons"] },
    { display: "too much screen time hurts your eyes", meaningZh: "屏幕时间太多伤眼睛", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Too much screen time hurts your eyes.", dims: ["health", "negative"] },
    { display: "save so much time", meaningZh: "节省大量时间", unitType: "collocation", difficulty: "basic", exampleEn: "Online tools save so much time.", dims: ["positive", "benefits"] },
  ],
  消费: [
    { display: "ads shape our spending habits", meaningZh: "广告塑造消费习惯", unitType: "sentence_frame", difficulty: "advanced", exampleEn: "Ads quietly shape our spending habits.", dims: ["advertising", "influences"] },
    { display: "donations should be voluntary", meaningZh: "捐赠应当自愿", unitType: "sentence_frame", difficulty: "advanced", exampleEn: "Donations should be voluntary, not forced.", dims: ["voluntariness", "opinion"] },
    { display: "the government's role", meaningZh: "政府的角色", unitType: "collocation", difficulty: "intermediate", exampleEn: "The government's role is to set the rules.", dims: ["government-role", "policies"] },
  ],
  老师: [
    { display: "keep parents in the loop", meaningZh: "让家长知情", unitType: "idiom", difficulty: "advanced", exampleEn: "Teachers keep parents in the loop.", dims: ["school-coop", "communication"] },
  ],
  社交媒体: [
    { display: "lurk more than post", meaningZh: "潜水多、发言少", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "I lurk more than I post.", dims: ["posting-browsing", "habits"] },
    { display: "cut back on screen time", meaningZh: "减少屏幕时间", unitType: "collocation", difficulty: "intermediate", exampleEn: "I'm cutting back on screen time.", dims: ["reducing", "self-control"] },
    { display: "spend way too much time", meaningZh: "花太多时间", unitType: "collocation", difficulty: "intermediate", exampleEn: "I spend way too much time scrolling.", dims: ["too-much", "time-spent"] },
  ],
  旅行建筑: [
    { display: "the highlight of the trip", meaningZh: "旅行中最精彩的部分", unitType: "collocation", difficulty: "intermediate", exampleEn: "The old bridge was the highlight of the trip.", dims: ["highlights", "interesting-point"] },
    { display: "a massive shopping complex", meaningZh: "大型购物中心", unitType: "collocation", difficulty: "intermediate", exampleEn: "They built a massive shopping complex nearby.", dims: ["which-mall", "facilities"] },
    { display: "do some sightseeing", meaningZh: "观光", unitType: "collocation", difficulty: "basic", exampleEn: "We did some sightseeing in the morning.", dims: ["trip", "activities"] },
    { display: "work in a foreign country", meaningZh: "在外国工作", unitType: "collocation", difficulty: "intermediate", exampleEn: "Working in a foreign country broadens your mind.", dims: ["country", "work-study"] },
    { display: "day-to-day duties", meaningZh: "日常工作职责", unitType: "collocation", difficulty: "advanced", exampleEn: "My day-to-day duties include filming.", dims: ["duties", "requirements"] },
  ],
  宠物动物: [
    { display: "interact with animals", meaningZh: "与动物互动", unitType: "collocation", difficulty: "intermediate", exampleEn: "Kids love interacting with animals.", dims: ["interactions", "lessons"] },
    { display: "not practical in a small apartment", meaningZh: "小公寓不现实", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Big dogs aren't practical in a small apartment.", dims: ["practicality", "city-pets"] },
  ],
  爱好: [
    { display: "my current hobbies include...", meaningZh: "我现在的爱好包括…", unitType: "sentence_frame", difficulty: "basic", exampleEn: "My current hobbies include hiking and chess.", dims: ["hobbies", "current-hobbies"] },
    { display: "I've always wanted to try...", meaningZh: "我一直想试试…", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "I've always wanted to try rock climbing.", dims: ["new-hobbies", "wish"] },
  ],
  阅读: [
    { display: "skim through", meaningZh: "浏览、略读", unitType: "phrasal_verb", difficulty: "intermediate", exampleEn: "I skim through the news in the morning.", dims: ["skimming", "careful-reading"] },
    { display: "read word by word", meaningZh: "逐字阅读", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "Contracts need reading word by word.", dims: ["careful-reading", "materials"] },
  ],
  人生阶段: [
    { display: "happiness means different things", meaningZh: "幸福的定义因人而异", unitType: "sentence_frame", difficulty: "intermediate", exampleEn: "Happiness means different things at different ages.", dims: ["definition", "stages"] },
    { display: "peer pressure", meaningZh: "同辈压力", unitType: "collocation", difficulty: "advanced", exampleEn: "Teenagers face a lot of peer pressure.", dims: ["pressures", "downsides"] },
  ],
  做得好的事情: [
    { display: "put in a lot of effort", meaningZh: "付出很多努力", unitType: "collocation", difficulty: "intermediate", exampleEn: "I put in a lot of effort for that exam.", dims: ["efforts", "process"] },
    { display: "the applause was worth it", meaningZh: "掌声让一切值得", unitType: "lexical_chunk", difficulty: "advanced", exampleEn: "Friends' applause was worth it.", dims: ["reactions", "feelings"] },
  ],
  与老人相处: [
    { display: "a wealth of experience", meaningZh: "丰富的经验", unitType: "collocation", difficulty: "advanced", exampleEn: "Elders offer a wealth of experience.", dims: ["wisdom", "benefits"] },
    { display: "see things from a different angle", meaningZh: "从不同角度看问题", unitType: "collocation", difficulty: "advanced", exampleEn: "Elders help you see things from a different angle.", dims: ["perspective", "lessons"] },
  ],
  国外旅行: [
    { display: "a road trip along the coast", meaningZh: "沿海公路旅行", unitType: "collocation", difficulty: "intermediate", exampleEn: "I dream of a road trip along the coast.", dims: ["country", "trip"] },
  ],
  家族企业: [
    { display: "run a family business", meaningZh: "经营家族企业", unitType: "collocation", difficulty: "intermediate", exampleEn: "His family runs a small breakfast shop.", dims: ["business", "duties"] },
  ],
  杂项: [
    { display: "tidy up", meaningZh: "收拾整洁", unitType: "phrasal_verb", difficulty: "basic", exampleEn: "I tidy up my desk every evening.", dims: ["tidy-or-not", "standard"] },
    { display: "a status symbol", meaningZh: "身份象征", unitType: "collocation", difficulty: "advanced", exampleEn: "Luxury watches are a status symbol.", dims: ["status-symbol", "reasons"] },
    { display: "wear a watch daily", meaningZh: "每天戴表", unitType: "collocation", difficulty: "basic", exampleEn: "I wear a watch daily out of habit.", dims: ["wear-or-not", "habits"] },
    { display: "a curious mind", meaningZh: "好奇的心", unitType: "collocation", difficulty: "intermediate", exampleEn: "Stargazing feeds a curious mind.", dims: ["curiosity", "interest"] },
    { display: "figure out how things work", meaningZh: "弄明白原理", unitType: "collocation", difficulty: "intermediate", exampleEn: "Science helps you figure out how things work.", dims: ["real-life", "application"] },
    { display: "sing in tune", meaningZh: "唱歌不跑调", unitType: "collocation", difficulty: "intermediate", exampleEn: "I can't sing in tune to save my life.", dims: ["singing-ability", "self-evaluation"] },
    { display: "get a big laugh", meaningZh: "引来大笑", unitType: "collocation", difficulty: "intermediate", exampleEn: "My jokes usually get a big laugh.", dims: ["reactions", "reactions-friends"] },
    { display: "wireless earbuds", meaningZh: "无线耳机", unitType: "collocation", difficulty: "intermediate", exampleEn: "Wireless earbuds are so convenient.", dims: ["wired-wireless", "types"] },
    { display: "harvest and share", meaningZh: "收获与分享", unitType: "collocation", difficulty: "intermediate", exampleEn: "We harvest vegetables and share them with neighbors.", dims: ["harvest", "sharing"] },
    { display: "tackle a real problem", meaningZh: "解决真实问题", unitType: "collocation", difficulty: "advanced", exampleEn: "Good laws tackle a real problem.", dims: ["problem", "targets"] },
    { display: "a sold-out stadium", meaningZh: "座无虚席的体育场", unitType: "collocation", difficulty: "advanced", exampleEn: "The match was in a sold-out stadium.", dims: ["event", "atmosphere"] },
    { display: "stay in touch", meaningZh: "保持联系", unitType: "collocation", difficulty: "intermediate", exampleEn: "We still stay in touch online.", dims: ["now", "contact"] },
    { display: "a turning point", meaningZh: "转折点", unitType: "collocation", difficulty: "intermediate", exampleEn: "That trip was a turning point for me.", dims: ["turning-point", "trigger"] },
    { display: "work out the solution", meaningZh: "想出解决办法", unitType: "collocation", difficulty: "intermediate", exampleEn: "We worked out the solution together.", dims: ["solving", "discovery"] },
    { display: "accepted my advice", meaningZh: "采纳了我的建议", unitType: "lexical_chunk", difficulty: "intermediate", exampleEn: "He accepted my advice in the end.", dims: ["acceptance", "outcome"] },
    { display: "left on read", meaningZh: "已读不回", unitType: "idiom", difficulty: "advanced", exampleEn: "Being left on read is so annoying.", dims: ["no-reply", "feelings"] },
    { display: "play the supporting role", meaningZh: "担当辅助角色", unitType: "collocation", difficulty: "advanced", exampleEn: "I played the supporting role in the team.", dims: ["your-role", "duties"] },
    { display: "get adjusted to", meaningZh: "适应", unitType: "collocation", difficulty: "intermediate", exampleEn: "I got adjusted to the new website quickly.", dims: ["your-adaptation", "changes"] },
    { display: "make a shopping list", meaningZh: "列购物清单", unitType: "collocation", difficulty: "basic", exampleEn: "I make a shopping list before I go.", dims: ["shopping-list", "habits"] },
    { display: "a quick nap", meaningZh: "小睡一会儿", unitType: "collocation", difficulty: "basic", exampleEn: "A quick nap recharges me.", dims: ["length", "benefits"] },
  ],
};
