import {describe,it,expect,vi,afterEach} from 'vitest';
import {projectSentenceEvent,emptySentencePractice,SentenceStudyError,type SentenceSession,type SentenceEvent} from '@/lib/sentence-study/contracts';
import {SentenceController,sentenceClient,sentenceErrorMessage,type SentenceClient,type SentenceBrowserContext} from '@/lib/sentence-study/client';

function initial():SentenceSession{return {id:'guided',scope:{type:'question',id:'q'},mode:'learn',status:'active',version:0,cards:[0,1].map(i=>({id:`s${i}`,version:'text1',materialId:'m',sentenceId:`unit${i}`,ordinal:i,chinese:'我想喝杯茶。',english:'I would like some tea.',contextZh:'',meaningOrigin:'user_chinese',usages:[],notes:[],progressVersion:0,source:{id:'a',questionId:'q',type:'ielts_practice',title:'喝什么',href:'/questions/q'}})),index:0,revealed:false,assessments:[],lastRatingEventId:null,nextDueAt:null,notice:null,experienceVersion:'guided-reveal-v1',stage:'recall',practice:emptySentencePractice()};}
let n=0;
function event(view:SentenceSession,type:string,extra:Record<string,unknown>={}):SentenceEvent{return {type,version:view.version,clientEventId:`event${++n}`,sentenceId:view.cards[view.index]?.id,unitVersion:view.cards[view.index]?.version,...extra} as SentenceEvent;}
function storage(){const data=new Map<string,string>();return {data,get length(){return data.size;},key:(i:number)=>[...data.keys()][i]??null,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);},removeItem:(k:string)=>{data.delete(k);}};}
function server(){let view=initial();const receipts=new Map<string,string>();const client:SentenceClient={overview:vi.fn(),create:vi.fn(async()=>view),get:vi.fn(async()=>structuredClone(view)),event:vi.fn(async(_id,e)=>{
  const payload=JSON.stringify(e);if(receipts.has(e.clientEventId)){if(receipts.get(e.clientEventId)!==payload)throw new SentenceStudyError('different payload',409,'event_conflict');return structuredClone(view);}
  if(e.version!==view.version)throw new SentenceStudyError('stale',409,'version_conflict');view=projectSentenceEvent(view,e);receipts.set(e.clientEventId,payload);return structuredClone(view);
})};return {client,read:()=>view};}

describe('guided sentence state machine',()=>{
  it('full progressive reveal does not enter teaching, score or complete',()=>{const v=initial(),next=projectSentenceEvent(v,event(v,'checkpoint',{revealCount:5,maxRevealCount:5,draft:'I want tea.',retryDraft:''}));expect(next.stage).toBe('recall');expect(next.revealed).toBe(false);expect(next.assessments).toEqual([]);expect(()=>projectSentenceEvent(next,event(next,'rate',{rating:'remembered'}))).toThrow();});
  it('keeps maximum exposure when re-covering, rejects out-of-range cursors',()=>{let v=initial();v=projectSentenceEvent(v,event(v,'checkpoint',{revealCount:4,maxRevealCount:4,draft:'I',retryDraft:''}));v=projectSentenceEvent(v,event(v,'checkpoint',{revealCount:0,maxRevealCount:0,draft:'I',retryDraft:''}));expect(v.practice?.maxRevealCount).toBe(4);expect(()=>projectSentenceEvent(v,event(v,'checkpoint',{revealCount:7,maxRevealCount:7,draft:'',retryDraft:''}))).toThrow();});
  it.each(['remembered','uncertain','forgot'])('%s stays on the sentence; explicit advance alone moves it',rating=>{let v=initial();v=projectSentenceEvent(v,event(v,'enter_teaching'));v=projectSentenceEvent(v,event(v,'rate',{rating}));expect(v).toMatchObject({index:0,stage:'rated',status:'active'});expect(v.assessments).toHaveLength(1);expect(()=>projectSentenceEvent(v,event(v,'rate',{rating}))).toThrow();v=projectSentenceEvent(v,event(v,'advance'));expect(v).toMatchObject({index:1,stage:'recall',revealed:false});expect(v.assessments).toHaveLength(1);});
  it('local retry never creates another assessment and pause/resume keeps its stage',()=>{let v=initial();for(const type of ['enter_teaching','rate','start_retry'])v=projectSentenceEvent(v,event(v,type,type==='rate'?{rating:'forgot'}:{}));v=projectSentenceEvent(v,event(v,'checkpoint',{revealCount:0,maxRevealCount:0,draft:'',retryDraft:'I would like tea.'}));v=projectSentenceEvent(v,{type:'pause',version:v.version,clientEventId:'pause'});v=projectSentenceEvent(v,{type:'resume',version:v.version,clientEventId:'resume'});expect(v).toMatchObject({stage:'retry',revealed:false,practice:{retryDraft:'I would like tea.'}});v=projectSentenceEvent(v,event(v,'reveal_retry'));expect(v.stage).toBe('retry_reveal');expect(v.assessments).toHaveLength(1);});
  it('last rating leaves a retry opportunity; completion requires advance',()=>{let v=initial();for(let i=0;i<2;i++){v=projectSentenceEvent(v,event(v,'enter_teaching'));v=projectSentenceEvent(v,event(v,'rate',{rating:'uncertain'}));expect(v.status).toBe('active');v=projectSentenceEvent(v,event(v,'advance'));}expect(v.status).toBe('completed');expect(v.assessments).toHaveLength(2);});
  it('legacy score advances as before; upgrading does not fabricate old assessments',()=>{let v=initial();delete v.experienceVersion;delete v.stage;delete v.practice;v=projectSentenceEvent(v,event(v,'reveal'));v=projectSentenceEvent(v,event(v,'rate',{rating:'remembered'}));expect(v.index).toBe(1);v=projectSentenceEvent(v,{type:'upgrade_experience',version:v.version,clientEventId:'upgrade'});expect(v).toMatchObject({index:1,stage:'recall',experienceVersion:'guided-reveal-v1'});expect(v.assessments).toHaveLength(1);});
});

describe('durable guided draft outbox',()=>{
  it('marks newly created guided events without rewriting historical receipts',async()=>{const s=server(),cache=storage(),c=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await c.load('guided');await c.apply({type:'enter_teaching'});await vi.waitFor(()=>expect(c.getSnapshot().pending).toBe(0));expect(vi.mocked(s.client.event).mock.calls[0][1]).toMatchObject({type:'enter_teaching',experienceVersion:'guided-reveal-v1'});c.dispose();});
  it('updates locally without per-key HTTP and coalesces concurrent flushes',async()=>{const s=server(),cache=storage(),c=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await c.load('guided');c.updatePractice({draft:'I'});c.updatePractice({draft:'I want',revealCount:2});expect(c.getSnapshot().view?.practice?.draft).toBe('I want');expect(s.client.event).not.toHaveBeenCalled();await Promise.all([c.flushPractice(),c.flushPractice()]);await vi.waitFor(()=>expect(c.getSnapshot().pending).toBe(0));expect(s.client.event).toHaveBeenCalledTimes(1);expect(s.read().practice?.revealCount).toBe(2);c.dispose();});
  it('refresh restores unsent draft on its sentence and entry flushes before teaching',async()=>{const s=server(),cache=storage(),a=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await a.load('guided');a.updatePractice({draft:'I would',revealCount:3});a.dispose();const b=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await b.load('guided');expect(b.getSnapshot().view?.practice?.draft).toBe('I would');await b.apply({type:'enter_teaching'});await vi.waitFor(()=>expect(b.getSnapshot().pending).toBe(0));expect(s.read()).toMatchObject({stage:'teaching',practice:{draft:'I would',maxRevealCount:3}});b.dispose();});
  it('an acknowledged older checkpoint does not wipe newer locally typed input',async()=>{const s=server(),cache=storage();let finish!:(v:SentenceSession)=>void;const send=s.client.event;s.client.event=vi.fn(async(id,e)=>{const response=await send(id,e);return new Promise<SentenceSession>(resolve=>{finish=()=>resolve(response);});});const c=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await c.load('guided');c.updatePractice({draft:'one'});await c.flushPractice();c.updatePractice({draft:'one two'});await vi.waitFor(()=>expect(finish).toBeTypeOf('function'));finish(s.read());await vi.waitFor(()=>expect(c.getSnapshot().pending).toBe(0));expect(c.getSnapshot().view?.practice?.draft).toBe('one two');c.dispose();});
  it('a second window cannot overwrite an unsent draft; explicit recovery uses the original receipt',async()=>{const s=server(),cache=storage(),a=new SentenceController(s.client,cache,{guided:true,writerId:'a'}),b=new SentenceController(s.client,cache,{guided:true,writerId:'b'});await a.load('guided');await b.load('guided');a.updatePractice({draft:'my original'});b.updatePractice({draft:'another tab'});expect(b.getSnapshot().conflict).toBe(true);await b.retry();expect(s.read().practice?.draft).toBe('my original');expect(s.read().assessments).toHaveLength(0);a.dispose();b.dispose();});
  it('storage failure keeps the page input but does not pretend it was saved',async()=>{const s=server(),cache=storage(),c=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await c.load('guided');const save=cache.setItem;cache.setItem=()=>{throw new DOMException('Quota exceeded','QuotaExceededError');};c.updatePractice({draft:'unsaved'});expect(c.getSnapshot().error).toContain('存储空间不足');expect(c.getSnapshot().error).toContain('尚未保存');expect(c.getSnapshot().view?.practice?.draft).toBe('unsaved');expect([...cache.data.keys()].some(k=>k.startsWith('sentence_practice:'))).toBe(false);expect(s.client.event).not.toHaveBeenCalled();expect(await c.apply({type:'enter_teaching'})).toBe(false);cache.setItem=save;await c.retry();await vi.waitFor(()=>expect(c.getSnapshot().pending).toBe(0));expect(s.read().practice?.draft).toBe('unsaved');c.dispose();});
});

function webLocks(){
  const held=new Set<string>();
  const request=vi.fn((name:string,_options:unknown,callback:(lock:Lock|null)=>unknown)=>{
    if(held.has(name))return Promise.resolve(callback(null));
    held.add(name);return Promise.resolve(callback({name,mode:'exclusive'} as Lock)).finally(()=>{held.delete(name);});
  }) as unknown as LockManager['request'];
  return {request};
}

describe('window identity and cloned sessionStorage',()=>{
  it('a duplicate tab rotates the cloned identity and cannot overwrite the original draft',async()=>{
    const s=server(),cache=storage(),tabA=storage(),tabB=storage(),locks=webLocks();tabA.setItem('roastduck_sentence_tab','copied-id');tabB.setItem('roastduck_sentence_tab','copied-id');
    const a=new SentenceController(s.client,cache,{guided:true,browser:{sessionStorage:tabA,locks}}),b=new SentenceController(s.client,cache,{guided:true,browser:{sessionStorage:tabB,locks}});
    await a.load('guided');await b.load('guided');expect(tabB.getItem('roastduck_sentence_tab')).not.toBe(tabA.getItem('roastduck_sentence_tab'));
    a.updatePractice({draft:'original in opener'});b.updatePractice({draft:'last input in duplicate'});expect(b.getSnapshot().conflict).toBe(true);
    const original=JSON.parse(cache.getItem('sentence_practice:guided:copied-id')!);expect(original.practice.draft).toBe('original in opener');
    const archived=[...cache.data.entries()].filter(([k])=>k.startsWith('sentence_conflict_draft:'));expect(archived).toHaveLength(1);expect(JSON.parse(archived[0][1]).practice.draft).toBe('last input in duplicate');
    a.dispose();b.dispose();
  });
  it('refresh reclaims the released identity and restores its unsent draft automatically',async()=>{
    const s=server(),cache=storage(),tab=storage(),locks=webLocks(),browser:SentenceBrowserContext={sessionStorage:tab,locks};
    const a=new SentenceController(s.client,cache,{guided:true,browser});await a.load('guided');const originalId=tab.getItem('roastduck_sentence_tab');a.updatePractice({draft:'restore after reload',revealCount:2});a.dispose();
    const b=new SentenceController(s.client,cache,{guided:true,browser});await b.load('guided');expect(tab.getItem('roastduck_sentence_tab')).toBe(originalId);expect(b.getSnapshot()).toMatchObject({conflict:false,error:null,view:{practice:{draft:'restore after reload',revealCount:2}}});b.dispose();
  });
  it('does not steal the opener draft when a duplicate loads after typing has started',async()=>{
    const s=server(),cache=storage(),tabA=storage(),tabB=storage(),locks=webLocks(),a=new SentenceController(s.client,cache,{guided:true,browser:{sessionStorage:tabA,locks}});await a.load('guided');a.updatePractice({draft:'keep this'});tabB.setItem('roastduck_sentence_tab',tabA.getItem('roastduck_sentence_tab')!);
    const b=new SentenceController(s.client,cache,{guided:true,browser:{sessionStorage:tabB,locks}});await b.load('guided');expect(b.getSnapshot().conflict).toBe(true);expect([...cache.data.entries()].filter(([k])=>k.startsWith('sentence_practice:'))).toHaveLength(1);a.dispose();b.dispose();
  });
  it('safely refuses browser writes if exclusive ownership is unavailable',async()=>{
    const s=server(),cache=storage(),c=new SentenceController(s.client,cache,{guided:true,browser:{sessionStorage:storage()}});await c.load('guided');expect(c.getSnapshot().error).toContain('多窗口草稿保护');expect(s.client.get).not.toHaveBeenCalled();expect(cache.data.size).toBe(0);c.dispose();
  });
});

describe('safe Chinese learning errors',()=>{
  afterEach(()=>{vi.unstubAllGlobals();});
  it.each([new TypeError('Failed to fetch'),new Error('NetworkError when attempting to fetch resource'),new DOMException('The operation was aborted','AbortError')])('keeps durable outbox state when %s',async error=>{
    const s=server(),cache=storage(),c=new SentenceController(s.client,cache,{guided:true,writerId:'tab'});await c.load('guided');s.client.event=vi.fn(async()=>{throw error;});await c.apply({type:'enter_teaching'});await vi.waitFor(()=>expect(c.getSnapshot().error).toBeTruthy());expect(c.getSnapshot().error).toContain('操作已保存在本机');expect(c.getSnapshot().error).not.toMatch(/Failed to fetch|NetworkError|AbortError|aborted/);expect(c.getSnapshot().pending).toBe(1);expect(c.getSnapshot().conflict).toBe(false);c.dispose();
  });
  it.each([new Error('quota'),new Error('storage full'),new DOMException('Exceeded storage quota','QuotaExceededError')])('translates local storage failure %s',error=>{expect(sentenceErrorMessage(error,'local')).toContain('尚未保存');expect(sentenceErrorMessage(error,'local')).not.toMatch(/quota|storage|QuotaExceeded/);});
  it('preserves actionable Chinese domain errors and rejects raw unknown English diagnostics',()=>{expect(sentenceErrorMessage(new SentenceStudyError('学习位置已变化，请恢复',409,'version_conflict'),'queued')).toBe('学习位置已变化，请恢复');expect(sentenceErrorMessage(new Error('internal secret diagnostics'))).not.toContain('internal');});
  it('the public client also returns Chinese transport failures before a controller is mounted',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>{throw new TypeError('Failed to fetch');}));await expect(sentenceClient.get('guided')).rejects.toThrow('连接不上');await expect(sentenceClient.create({scope:{type:'all'},mode:'learn',clientRequestId:'same-request'})).rejects.toThrow('尚未确认保存结果');});
  it('does not show an HTML/invalid JSON error body as a learning instruction',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('<html>upstream failure</html>',{status:502})));await expect(sentenceClient.get('guided')).rejects.toThrow('无法读取的结果');});
});
