import {useEffect,useState} from 'react';
import type {AppServices} from '@/lib/app-services';
import type {AppMemory,MemoryJob} from '@/lib/app-services/memory';
export function MemoryPage({app}:{app:AppServices}){
  const [rows,setRows]=useState<AppMemory[]>([]),[jobs,setJobs]=useState<MemoryJob[]>([]),[query,setQuery]=useState(''),[inactive,setInactive]=useState(false),[error,setError]=useState(''),[tick,setTick]=useState(0);
  useEffect(()=>{let live=true;void Promise.all([app.memory.list(query,inactive),app.memory.jobs()]).then(([rows,jobs])=>{if(live){setRows(rows);setJobs(jobs);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[app,query,inactive,tick]);
  async function action(work:()=>Promise<unknown>){try{await work();setTick(t=>t+1);setError('');}catch(e){setError(e instanceof Error?e.message:'操作未完成，请重试');}}
  return <><header className="page-heading"><h1>Chloe 记得什么</h1></header><p>仅保存你明确表达的稳定信息。随时编辑、撤销或删除，不删除原聊天。</p><input type="search" aria-label="搜索记忆" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索记忆"/><label className="check-label"><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/>也查看已撤销、删除与旧版本</label>{error&&<p role="alert" className="error-box">{error}</p>}
    {!!jobs.length&&<section><h2>记忆整理待继续</h2><p className="quiet">不影响聊天。恢复已有结果优先；未知请求不会自动重发。</p>{jobs.map(job=><div className="setting-row" key={job.id}><span>{job.status==='failed'?'上次整理未完成':'有一项整理待恢复'}</span><button onClick={()=>void action(()=>app.memory.retry(job.id,{retryFailed:true}))}>恢复</button>{job.error_code==='result_unknown'&&<button onClick={()=>{if(confirm('重新请求可能再次产生费用。确认继续？'))void action(()=>app.memory.retry(job.id,{retryUnknown:true,retryFailed:true}));}}>确认重试</button>}</div>)}</section>}
    {rows.map(memory=><article className="material-row" key={memory.id}><p>{memory.summary}</p><small className="quiet">{memory.status==='active'?'正在使用':memory.status==='superseded'?'已被新版本替代':'已撤销或删除'} · {new Date(memory.updated_at).toLocaleDateString('zh-CN')}</small><details><summary>来源证据</summary><p>{memory.source_type==='user_edit'?'你的编辑':'聊天中的明确表达'}；置信度 {Math.round(memory.confidence*100)}%</p></details><div className="row-actions">{memory.status==='active'?<><button onClick={()=>{const summary=prompt('修改这条记忆',memory.summary);if(summary)void action(()=>app.memory.edit(memory.id,{clientEventId:crypto.randomUUID(),summary,category:memory.category}));}}>编辑</button><button onClick={()=>void action(()=>app.memory.state(memory.id,'dismissed'))}>撤销</button><button onClick={()=>void action(()=>app.memory.state(memory.id,'deleted'))}>删除</button></>:memory.status!=='superseded'&&<button onClick={()=>void action(()=>app.memory.state(memory.id,'active'))}>恢复这条</button>}</div></article>)}
    {!rows.length&&<p className="quiet">没有匹配的记忆。</p>}<button onClick={()=>{if(confirm('清空长期记忆并取消待处理提取？原聊天与学习进度保留。'))void action(()=>app.memory.clear());}}>清空记忆</button></>;
}
export function ExpressionsPage({app}:{app:AppServices}){
  const [query,setQuery]=useState(''),[rows,setRows]=useState<Awaited<ReturnType<AppServices['expressions']['list']>>>([]),[error,setError]=useState(''),[tick,setTick]=useState(0);
  useEffect(()=>{let live=true;void app.expressions.list(query).then(rows=>{if(live)setRows(rows);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[app,query,tick]);
  return <><header className="page-heading"><h1>查找我的表达</h1></header><input type="search" aria-label="搜索表达" value={query} onChange={e=>setQuery(e.target.value)} placeholder="中文意思或英文表达"/>{error&&<p role="alert" className="error-box">{error}</p>}{rows.map(row=><article className="material-row" key={row.itemId}><h2>{row.chinese}</h2><p className="material-target" lang="en">{row.english}</p><p lang="en">{row.sentenceEn}</p><p>{row.sentenceZh}</p><small className="quiet">{row.sourceTitle}</small><div className="row-actions"><a href={`#/light-study?scope=material&id=${encodeURIComponent(row.materialId)}`} className="text-button">学习这些表达</a><button onClick={()=>{const remark=prompt(row.note?'编辑备注':'收藏时可以补充备注',row.note?.user_remark??'');if(remark!==null)void app.settings.saveNote({id:row.note?.id,itemId:row.itemId,surface:row.english,meaningZh:row.chinese,remark}).then(()=>setTick(t=>t+1)).catch(e=>setError(e.message));}}>{row.note?'编辑收藏':'收藏表达'}</button></div></article>)}{!rows.length&&<p className="quiet">没有匹配的已审核表达。不会为了搜索重新生成材料。</p>}</>;
}
