import {useEffect,useState} from 'react';
import type {AppServices} from '@/lib/app-services';
import {nativeSync,previewComputer,syncWithComputer,type PairingStatus} from '@/lib/platform/android/device-sync';
export function SyncPage({app}:{app:AppServices}){
  const [status,setStatus]=useState<PairingStatus>({}),[info,setInfo]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[manifest,setManifest]=useState<Awaited<ReturnType<typeof previewComputer>>|null>(null),[tasks,setTasks]=useState<Awaited<ReturnType<AppServices['sync']['remoteTasks']>>>([]);
  useEffect(()=>{let alive=true;void nativeSync.status().then(value=>{if(alive)setStatus(value);}).catch(e=>{if(alive)setError(e.message);});void app.sync.remoteTasks().then(rows=>{if(alive)setTasks(rows);});return()=>{alive=false;};},[app]);
  async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'同步未完成，请重试');}finally{setBusy(false);}}
  async function begin(pairingInfo:string){setStatus(await nativeSync.begin({pairingInfo:pairingInfo.trim(),localDeviceId:app.identity.device_id}));setInfo('');}
  return <><header className="page-heading"><h1>连接我的电脑</h1></header><p>两台设备连接同一 Wi-Fi，在电脑的“设置→连接手机”开启连接。资料保留在两端，不同步 API Key。</p>{error&&<div role="alert" className="error-box">{error}</div>}{!status.peer&&!status.pending&&<><button className="primary-button" disabled={busy} onClick={()=>void action(async()=>{const scanned=await nativeSync.scan();if(scanned.pairingInfo)await begin(scanned.pairingInfo);})}>扫描电脑配对码</button><details className="details"><summary>手动输入配对信息</summary><textarea aria-label="电脑配对信息" value={info} onChange={e=>setInfo(e.target.value)} placeholder="粘贴电脑上显示的 roastduck-pair:…"/><button disabled={busy||!info.trim()} onClick={()=>void action(()=>begin(info))}>开始配对</button></details></>}
    {status.pending&&<section className="status-panel"><h2>确认是你的电脑</h2><p>两端确认码：<strong>{status.pending.verification||'正在恢复配对请求'}</strong></p><p>请在电脑确认相同的数字，然后继续。</p><button className="primary-button" disabled={busy} onClick={()=>void action(async()=>{const result=await nativeSync.finish();setStatus(result);if(result.peer)setManifest(await previewComputer());})}>电脑已确认，继续</button><button disabled={busy} onClick={()=>void action(async()=>setStatus(await nativeSync.forget()))}>取消这次配对</button></section>}
    {status.peer&&<section><h2>已配对的电脑</h2><p className="quiet">{status.peer.url}</p><button disabled={busy} onClick={()=>void action(async()=>setManifest(await previewComputer()))}>查看可同步资料</button>{manifest&&<><p>电脑已有 {manifest.counts.questions??0} 道题、{manifest.counts.speaking_question_attempts??0} 次回答、{manifest.counts.practice_materials??0} 份材料、{manifest.counts.light_study_progress??0} 项轻学习记录。</p><p className="quiet">直接导入已有内容，不重新分析历史回答。音频仅传已有缓存。</p></>}<button className="primary-button" disabled={busy||!manifest} onClick={()=>void action(async()=>{const result=await syncWithComputer(app.sync,setProgress);setProgress(`同步完成：接收 ${result.received}、发送 ${result.sent} 条变更记录。`);setTasks(await app.sync.remoteTasks());})}>立即同步</button></section>}
    {progress&&<p role="status">{progress}</p>}{status.peer&&<div className="row-actions"><a className="primary-button" href="#/">回到今天，开始学习</a><button disabled={busy} onClick={()=>{if(confirm('断开本机配对？已有学习资料保留；电脑可另行撤销该设备。'))void action(async()=>{setStatus(await nativeSync.forget());setManifest(null);});}}>断开配对</button></div>}
    {!!tasks.length&&<section><h2>另一台设备的任务</h2>{tasks.filter(task=>task.entity!=='practice_materials').map(task=><div className="setting-row" key={task.entity+task.record_key}><span>{task.entity==='light_study_sessions'?'轻松学':'四步强化'} · {task.paused?'原设备已暂停':'仍由原设备使用'}</span>{!!task.paused&&<button disabled={busy} onClick={()=>void action(async()=>{await app.sync.claim(task.entity,task.record_key);setTasks(await app.sync.remoteTasks());setProgress('已在本机接续，可以回到学习入口继续。下次同步会告知电脑。');})}>在本机接续</button>}</div>)}</section>}</>;
}
