'use client';
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import Image from 'next/image';
type View={interfaces:Array<{name:string;address:string}>;connection:null|{enabled:boolean;url:string;pairingInfo:string;expiresAt:number;pending:null|{id:string;name:string;verification:string;approved:boolean;expiresAt:number};peers:Array<{deviceId:string;name:string;revoked:boolean}>}};
export function DeviceSyncSettings(){
  const [view,setView]=useState<View|null>(null),[host,setHost]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[qr,setQr]=useState('');
  async function refresh(){const response=await fetch('/api/device-sync');const result=await response.json();if(!response.ok)throw new Error(result.error);setView(result);setHost(current=>current||result.interfaces[0]?.address||'');}
  useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(timer);},[]);
  const info=view?.connection?.pairingInfo;
  useEffect(()=>{let current=true;if(info)void QRCode.toDataURL(info,{width:320,margin:2,errorCorrectionLevel:'M'}).then(value=>{if(current)setQr(value);}).catch(()=>{if(current)setError('二维码暂不可用，可以复制配对信息');});return()=>{current=false;};},[info]);
  async function action(type:string,id?:string){setBusy(true);setError('');try{const response=await fetch('/api/device-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,host,id})}),result=await response.json();if(!response.ok)throw new Error(result.error);setView(result);}catch(e){setError(e instanceof Error?e.message:'操作未完成');}finally{setBusy(false);}}
  return <section className="ui-panel"><h2>连接我的安卓手机</h2><p>两台设备连接同一私人 Wi-Fi。仅在这里主动开启同步；不会开放整个 Web 后台，也不会同步 API Key。</p>{error&&<p role="alert">{error}</p>}{!view?.connection?<><label>本机网络<select value={host} onChange={e=>setHost(e.target.value)}>{view?.interfaces.map(item=><option key={item.address} value={item.address}>{item.name} · {item.address}</option>)}</select></label><button className="ui-button primary" disabled={busy||!host} onClick={()=>void action('start')}>开启连接手机</button><p>如果 Windows 询问防火墙权限，只允许私人网络。不要在公共 Wi-Fi 开启。</p></>:<><p>同步地址：{view.connection.url}</p>{view.connection.expiresAt>Date.now()?<>{/* Generated local QR, not a remotely loaded image. */}
      {qr&&<Image unoptimized src={qr} alt="用鱼块安卓 App 扫描配对" width={320} height={320} style={{maxWidth:'100%',height:'auto'}}/>}<details><summary>无法扫码？复制配对信息</summary><textarea readOnly aria-label="配对信息" value={view.connection.pairingInfo}/><p>包含一次性凭据，不要发给其他人。五分钟后失效。</p></details></>:<button disabled={busy} onClick={()=>void action('renew')}>显示新的配对码</button>}{view.connection.pending&&!view.connection.pending.approved&&<section><h3>确认连接：{view.connection.pending.name}</h3><p>请确认手机也显示：<strong>{view.connection.pending.verification}</strong></p><button disabled={busy} onClick={()=>void action('approve',view.connection!.pending!.id)}>两端相同，允许配对</button></section>}<button disabled={busy} onClick={()=>void action('stop')}>关闭局域网同步</button>{view.connection.peers.map(peer=><p key={peer.deviceId}>{peer.name} · {peer.revoked?'已撤销':<button disabled={busy} onClick={()=>void action('revoke',peer.deviceId)}>撤销这台设备</button>}</p>)}</>}</section>;
}
