import type {Db} from '@db/client';
import {authoredMaterialSchema,authorHash,expandAuthored,type RecoverySource,type OfflineReview} from '@/lib/four-step/offline-contracts';
/** Original synthetic lesson with an actual multi-sentence, independently labelled Mock evidence chain. */
export async function publishSentenceFixture(db:Db,id:string,targets:Array<[string,string]>){
  const schema=await import('@db/schema'),englishParts=targets.map((_,i)=>`For item ${i+1}, I want to do that.`),meanings=targets.map(([,zh])=>`我想${zh}。`),english=englishParts.join(' '),chinese=meanings.join('\n');
  await db.insert(schema.questions).values({id,bookId:'retired',part:1,text:'How would you describe your day?',textZh:'你会怎样描述这一天？',normText:id}).onConflictDoNothing();
  await db.insert(schema.speakingQuestionAttempts).values({id:`answer-${id}`,questionId:id,mode:'practice',answerText:english,intendedMeaningZh:chinese,status:'processing'});
  const offsets=(parts:string[],join:string)=>parts.map((text,index)=>({index,text,start:parts.slice(0,index).join(join).length+(index?join.length:0),end:parts.slice(0,index).join(join).length+(index?join.length:0)+text.length}));
  const source:RecoverySource={index:0,key:`answer-${id}`,kind:'attempt',hash:`synthetic-${id}`,createdAt:new Date().toISOString(),mode:'practice',questionId:id,questionEn:'How would you describe your day?',questionZh:'你会怎样描述这一天？',part:1,english,chinese,en:offsets(englishParts,' '),zh:offsets(meanings,'\n'),spokenStyleVersion:'personal-spoken-v2'};
  const author=authoredMaterialSchema.parse({index:0,sourceHash:source.hash,contextId:`synthetic-sentence-author-${id}`,model:'synthetic lesson author',units:targets.map(([en,zh],i)=>({en:[i],zh:[i],intent:meanings[i],status:'missing',reason:'合成准备意图，英文占位没有表达中文动作。',english:`I want to ${en}.`,gaps:[{cue:zh,target:en,quote:meanings[i],why:'中文给定了具体动作，作为准备项。',surface:en,kind:'unexpressed_intention',senseKey:`fixture-${en.replaceAll(' ','-')}`,recallPromptZh:meanings[i],recallAnswerEn:`I want to ${en}.`}]}))});
  const expanded=expandAuthored(source,author);
  const selection={approved:true,reasonZh:'独立合成资料审核',units:expanded.diagnosis.units.map(u=>({unitId:u.id,status:'missing' as const,evidenceQuote:u.chinese[0].text,reasonZh:'合成中文原意明确，提供准备项。'})),gaps:expanded.diagnosis.units.flatMap(u=>u.gaps.map(g=>({gapId:g.id,decision:'train' as const,evidenceQuote:g.evidenceQuote,reasonZh:'合成准备意图。'})))};
  const review:OfflineReview={authorHash:authorHash(author),contextId:`synthetic-sentence-reviewer-${id}`,model:'synthetic lesson reviewer',selection,review:{approved:true,reasonZh:'逐句原意与自然英语的合成审核',rows:expanded.draft.rows.map(r=>({gapId:r.gapId,approved:true,evidenceQuote:expanded.diagnosis.units.find(u=>u.gaps.some(g=>g.id===r.gapId))!.chinese[0].text,reasonZh:'准备项和当前完整意思对应。',repairNeeded:false,learningTargetNeeded:true,meaningPreserved:true,minimalRepair:true,cueUnambiguous:true,sentenceAligned:true,clozeValid:true,recallCueUnambiguous:true,recallAnswerConcrete:true,recallAligned:true})),wholeAnswer:{meaningPreserved:true,voicePreserved:true,stancePreserved:true,discourseFunctionsPreserved:true,metaphorsPreserved:true,spokenNaturalness:true,noInventedPersonalStyle:true,reasonZh:'全部原始合成意思逐句保留。',evidence:expanded.draft.sentences.slice(0,24).map((s,i)=>({sourceField:'intendedMeaningZh' as const,sourceQuote:meanings[i],rendering:s.english,treatment:'adapted' as const,reasonZh:'保留中文动作。'}))},sentences:expanded.draft.sentences.map((s,i)=>({sentenceId:s.id,sentenceQuote:s.english,meaningPreserved:true,naturalEnglish:true,grammarCorrect:true,sourceUncertaintyHandled:true,reasonZh:'本句为对应动作的完整自然英语。',evidence:[{sourceField:'intendedMeaningZh' as const,sourceQuote:meanings[i]}]}))}};
  return (await import('@/lib/four-step/offline-apply')).applyOfflineMaterial(source,author,review);
}
