import fs from 'node:fs/promises';
import path from 'node:path';
import {X509Certificate} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
export function privateIPv4(address:string,allowLoopback=false){
  if(!/^(0|[1-9]\d{0,2})(\.(0|[1-9]\d{0,2})){3}$/.test(address))return false;
  const octets=address.split('.').map(Number);if(octets.some(n=>n>255))return false;
  return octets[0]===10||octets[0]===192&&octets[1]===168||octets[0]===172&&octets[1]>=16&&octets[1]<=31||allowLoopback&&octets[0]===127;
}
export async function syncCertificate(directory:string,host:string){
  if(!privateIPv4(host,true))throw new Error('只允许绑定本机私有 IPv4 地址');
  await fs.mkdir(directory,{recursive:true,mode:0o700});
  const certPath=path.join(directory,'server.crt'),keyPath=path.join(directory,'server.key');
  try{
    const cert=await fs.readFile(certPath),key=await fs.readFile(keyPath),x509=new X509Certificate(cert);
    if(x509.checkIP(host)&&Date.parse(x509.validTo)>Date.now()+86400000)return {cert,key,fingerprint:x509.fingerprint256.replaceAll(':','').toLowerCase()};
    throw new Error('已配对证书不覆盖当前地址或即将过期，请在原网络使用，或明确重置配对证书');
  }catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  // No certificate store or system trust changes. The child emits only non-secret diagnostics.
  const candidates=process.platform==='win32'?['C:/Program Files/Git/usr/bin/openssl.exe','C:/Program Files/Git/mingw64/bin/openssl.exe']:['/usr/bin/openssl'];
  let binary:string|undefined;for(const candidate of candidates)if(await fs.stat(candidate).then(s=>s.isFile(),()=>false)){binary=candidate;break;}
  if(!binary)throw new Error('未找到本机 OpenSSL，不能建立安全同步；未启用未加密连接');
  const temporary=await fs.mkdtemp(path.join(directory,'certificate-'));
  await promisify(execFile)(binary,['req','-x509','-newkey','rsa:3072','-nodes','-sha256','-days','365','-subj','/CN=RoastDuck Local Sync','-addext',`subjectAltName=IP:${host},DNS:localhost`,'-keyout',path.join(temporary,'key.pem'),'-out',path.join(temporary,'cert.pem')],{windowsHide:true,timeout:30000});
  const cert=await fs.readFile(path.join(temporary,'cert.pem')),key=await fs.readFile(path.join(temporary,'key.pem'));
  await fs.copyFile(path.join(temporary,'key.pem'),keyPath,fs.constants.COPYFILE_EXCL);await fs.chmod(keyPath,0o600);await fs.copyFile(path.join(temporary,'cert.pem'),certPath,fs.constants.COPYFILE_EXCL);
  // Keep only the canonical private key; remove exact files generated by this operation.
  await fs.unlink(path.join(temporary,'key.pem'));await fs.unlink(path.join(temporary,'cert.pem'));await fs.rmdir(temporary);
  return {cert,key,fingerprint:new X509Certificate(cert).fingerprint256.replaceAll(':','').toLowerCase()};
}
